# this file allow us to request 
@SchoolAPI_HostAddress = http://localhost:5000

GET {{SchoolAPI_HostAddress}}/api/Student/students
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMTU5NzM4Yy02YWJhLTQ0ZWYtOWUwNC0yNGI1ZmZmNTM2ODQiLCJlbWFpbCI6ImFkbWluQHNjaG9vbC5jb20iLCJuYW1lIjoiQWRtaW4gVXNlciIsImp0aSI6IjZiNTg4NmI0LWViNDItNDBjZi05NWM1LWQxMTQ0MzljMWRiNCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzYzODIzMjM2LCJpc3MiOiJzY2hvb2xBUEkiLCJhdWQiOiJzY2hvb2xDbGllbnQifQ.CzRFJOK6tOsoVexKvTGpmpb8EDrRbZWUHxn1H5cKKyM

###
#

GET {{SchoolAPI_HostAddress}}/api/class/classes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMTU5NzM4Yy02YWJhLTQ0ZWYtOWUwNC0yNGI1ZmZmNTM2ODQiLCJlbWFpbCI6ImFkbWluQHNjaG9vbC5jb20iLCJuYW1lIjoiQWRtaW4gVXNlciIsImp0aSI6IjZiNTg4NmI0LWViNDItNDBjZi05NWM1LWQxMTQ0MzljMWRiNCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzYzODIzMjM2LCJpc3MiOiJzY2hvb2xBUEkiLCJhdWQiOiJzY2hvb2xDbGllbnQifQ.CzRFJOK6tOsoVexKvTGpmpb8EDrRbZWUHxn1H5cKKyM

###

GET {{SchoolAPI_HostAddress}}/api/Buggy/server-error
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMTU5NzM4Yy02YWJhLTQ0ZWYtOWUwNC0yNGI1ZmZmNTM2ODQiLCJlbWFpbCI6ImFkbWluQHNjaG9vbC5jb20iLCJuYW1lIjoidmVhc25ha29ldW4iLCJqdGkiOiIzMmRhYjllZi02MWNlLTRkMmEtYTllNS0zYjIxOWQ2MjdjZDkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiQWRtaW4iLCJUZWFjaGVyIl0sImV4cCI6MTc2NjY1NTM2OSwiaXNzIjoic2Nob29sQVBJIiwiYXVkIjoic2Nob29sQ2xpZW50In0.EOxvggKFWjYtL--tUENjqhXo_DQTPe9wB6fgWzdf81k