server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Fallback routing for Single Page Applications (Angular)
    location / {
        try_files $uri $uri/ /index.html;
    }
}